from django.urls import path, include
from django.contrib.auth import views as auth_views

from .views import (
    game_search,
    home,
    all,
    graphs_home,
    graphs_by_gender,
    backup_db,
    restore_db,
    backup_management,
    backup_help,
    registrar_usuario,
    view_db_schema,
    game_management_home,
    create_game,
    search_and_edit_game,
    edit_game,
    complete_description,
    index_management,
    game_details_ajax,
)

urlpatterns = [
    path("", home, name="home"),
    path("search/", game_search, name="game_search"),
    path("all/", all, name="all_games"),
    path("graphs/", graphs_home, name="graphs_home"),
    path("graphs-by-gender/", graphs_by_gender, name="graphs_by_gender"),
    path("register/", registrar_usuario, name="register"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("backup/", backup_db, name="backup_db"),
    path("restore/", restore_db, name="restore_db"),
    path("backup-management/", backup_management, name="backup_management"),
    path("backup-help/", backup_help, name="backup_help"),
    path("db_schema/", view_db_schema, name="db_schema"),
    path("games/", game_management_home, name="game_management_home"),
    path("games/create/", create_game, name="create_game"),
    path("games/search/", search_and_edit_game, name="search_and_edit_game"),
    path("games/edit/<str:app_id>/", edit_game, name="edit_game"),
    path(
        "games/description/<str:app_id>/",
        complete_description,
        name="complete_description",
    ),
    path("index-manager/", index_management, name="index_manager"),
    path("api/game/<str:app_id>/", game_details_ajax, name="game_details_ajax"),
]
