--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categories; Type: TABLE; Schema: steam; Owner: postgres
--

CREATE TABLE steam.categories (
    id bigint NOT NULL,
    category text,
    app_id text
);


ALTER TABLE steam.categories OWNER TO postgres;

--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: steam; Owner: postgres
--

ALTER TABLE steam.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME steam.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: steam; Owner: postgres
--

ALTER TABLE ONLY steam.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: categories_app_id_9f8cfe91; Type: INDEX; Schema: steam; Owner: postgres
--

CREATE INDEX categories_app_id_9f8cfe91 ON steam.categories USING btree (app_id);


--
-- Name: categories_app_id_9f8cfe91_like; Type: INDEX; Schema: steam; Owner: postgres
--

CREATE INDEX categories_app_id_9f8cfe91_like ON steam.categories USING btree (app_id text_pattern_ops);


--
-- Name: categories categories_app_id_9f8cfe91_fk_games_app_id; Type: FK CONSTRAINT; Schema: steam; Owner: postgres
--

ALTER TABLE ONLY steam.categories
    ADD CONSTRAINT categories_app_id_9f8cfe91_fk_games_app_id FOREIGN KEY (app_id) REFERENCES steam.games(app_id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

