# Generated by Django 5.2 on 2025-05-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('appid', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('estimated_owners', models.TextField(blank=True, null=True)),
                ('peak_ccu', models.IntegerField(blank=True, null=True)),
                ('required_age', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_dlc_count', models.IntegerField(blank=True, null=True)),
                ('about_the_game', models.TextField(blank=True, null=True)),
                ('supported_languages', models.TextField(blank=True, null=True)),
                ('full_audio_languages', models.TextField(blank=True, null=True)),
                ('reviews', models.TextField(blank=True, null=True)),
                ('header_image', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('support_url', models.TextField(blank=True, null=True)),
                ('support_email', models.TextField(blank=True, null=True)),
                ('windows', models.BooleanField(default=False)),
                ('mac', models.BooleanField(default=False)),
                ('linux', models.BooleanField(default=False)),
                ('metacritic_score', models.IntegerField(blank=True, null=True)),
                ('metacritic_url', models.TextField(blank=True, null=True)),
                ('user_score', models.FloatField(blank=True, null=True)),
                ('positive', models.IntegerField(blank=True, null=True)),
                ('negative', models.IntegerField(blank=True, null=True)),
                ('score_rank', models.IntegerField(blank=True, null=True)),
                ('achievements', models.IntegerField(blank=True, null=True)),
                ('recommendations', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('average_playtime_forever', models.IntegerField(blank=True, null=True)),
                ('average_playtime_two_weeks', models.IntegerField(blank=True, null=True)),
                ('median_playtime_forever', models.IntegerField(blank=True, null=True)),
                ('median_playtime_two_weeks', models.IntegerField(blank=True, null=True)),
                ('developers', models.TextField(blank=True, null=True)),
                ('publishers', models.TextField(blank=True, null=True)),
                ('categories', models.TextField(blank=True, null=True)),
                ('genres', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('screenshots', models.TextField(blank=True, null=True)),
                ('movies', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'db_table': 'game',
            },
        ),
    ]
