# Generated by Django 5.2 on 2025-05-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.CharField(blank=True, max_length=50, null=True)),
                ('estimated_owners', models.CharField(blank=True, max_length=50, null=True)),
                ('peak_ccu', models.IntegerField(default=0)),
                ('required_age', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('about_game', models.TextField(blank=True, null=True)),
                ('developers', models.TextField(blank=True, null=True)),
                ('publishers', models.TextField(blank=True, null=True)),
                ('categories', models.TextField(blank=True, null=True)),
                ('genres', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('screenshots', models.TextField(blank=True, null=True)),
                ('movies', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
