# Generated by Django 5.2 on 2025-06-12 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_add_default_genres'),
        ('games', '0002_genre'),
    ]

    operations = [
    ]
