# Generated by Django 5.2 on 2025-06-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_merge_0002_add_default_genres_0002_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genres',
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='games', to='games.genre'),
        ),
    ]
